1)Create a NumPy array of integers from 1 to 10

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create a 2x3 NumPy array filled with zeros

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

3. Create a NumPy array of even numbers from 2 to 20.

In [ ]:
arr2=np.arange(2,21,2)
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [ ]:
arr2 = np.array([4, 5, 6])
arr2

array([4, 5, 6])

In [ ]:
arr3=arr1+arr2
arr3

array([5, 7, 9])

In [ ]:
arr4=arr2-arr1
arr4

array([3, 3, 3])

In [ ]:
arr5=arr2*arr1
arr5

array([ 4, 10, 18])

In [ ]:
arr6=arr2/arr1
arr6

array([4. , 2.5, 2. ])

5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.


In [ ]:
np.random.randint(0,100,100)

array([45, 93, 22, 82, 45, 97, 63,  8, 89, 25, 30, 81, 98, 68, 58, 26, 92,
       72, 97, 45, 23, 22, 17, 15, 95, 87, 82, 65, 39, 32, 35,  7, 21, 34,
       92, 20,  6,  7, 63, 12, 70, 95, 53, 48, 22, 45,  0, 95, 97, 26, 54,
       25, 65, 98, 81, 58, 22,  7, 27, 53, 66, 26, 32, 15,  8, 93, 33, 15,
       32, 76, 60, 91, 63, 76, 68, 23,  9, 68, 84, 50, 91, 67, 97, 67, 24,
       60, 44, 98, 34, 70,  7,  2, 43, 42, 64, 97,  2, 90, 36,  7])

In [ ]:
arr1=np.random.randint(0,100,100)

In [ ]:
arr1.mean()

52.06

6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).


In [ ]:
arr2=np.random.randint(0,20,12)
arr2

array([15,  9,  2,  0, 10, 10,  4,  9,  2,  0,  3,  5])

In [ ]:
arr2.reshape(3,4)

array([[15,  9,  2,  0],
       [10, 10,  4,  9],
       [ 2,  0,  3,  5]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions

In [ ]:
 arr = np.array([1, 2, 3, 4, 5])
 arr

array([1, 2, 3, 4, 5])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

8. Create a 5x5 identity matrix using NumPy

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

 9)Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
a*b

array([ 4, 10, 18])

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.


In [ ]:
arr1=np.arange(0,21)

In [ ]:
arr1.reshape(3,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [ ]:
arr1.max()

20

In [ ]:
arr1.min()

0

11.Concatenate two random NumPy arrays horizontally and vertically

In [ ]:
a=np.zeros((3,3))

In [ ]:
b=np.ones((3,3))

In [ ]:
np.vstack([a,b])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.hstack([a,b])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

12.Given a 2D NumPy array, calculate the sum of each row and each column
separately

In [ ]:
arr1=np.arange(1,21)

In [ ]:
arr1.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

15)create a numpy array with random integers between 1 and 100 and then sort in ascending order?

In [2]:
import numpy as np
arr=np.random. randint(1,101,size=10)
arr.sort()
print(arr)

[19 21 30 34 35 49 64 79 91 95]


16)
Calculate the elemen-twise absolute difference between two Numpy arrays?

In [4]:
import numpy as np
arr1=np.array([8,10,19,15])
arr2=np.array([6,8,10,12])

In [5]:
abs_diff=np.abs(arr1-arr2)
print(abs_diff)

[2 2 9 3]


17)Given a 2D NumPy array, extract the first row and the last column.


In [6]:
arr1=np.array([[10,1,14,16,18,20],
[22,24,26,28,30,32],
[34,36,38,40,42,44],
[46,48,50,52,54,56],
[58,60,62,64,66,68],
[70,72,74,76,78,80]])

In [8]:
arr1

array([[10,  1, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [9]:
arr[0]

19

18.Slice a 1D NumPy array to get every other elemennt





In [10]:
arr=(20,11,12,21,19,25,23,30,50)

In [11]:
arr[:2]

(20, 11)

In [12]:
arr[1:5]

(11, 12, 21, 19)

19).Given a 2D NumPy array, extract a subarray consisting of the central 2x2 elements


In [16]:
import numpy as np
arr4=np.array([[1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]])
subarray=arr4[1:3,2:4]
print(subarray)

[[ 7  8]
 [11 12]]


20)Reverse a 1D NumPy array using slicing.

In [17]:
import numpy as np
arr=np.array([1,2,3,4,5])

In [18]:
reversed_array=arr[::-1]
print(reversed_array)

[5 4 3 2 1]
